use_frameworks!

target 'AttributedText_Example' do
  pod 'AttributedText', :path => '../'

#  target 'AttributedText_Tests' do
#    inherit! :search_paths
#
#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
#  end
end
